"""
Sector 10 — Discovery Economy (engines 91–100).

AI-generated discoveries, inventions, and innovations become commercially
tradeable through licensing, venture partnerships, and IP markets.
"""

from monetization.sectors.base import RevenueEngine, RevenueModel

DISCOVERY_ECONOMY_ENGINES = [
    RevenueEngine(
        engine_id=91,
        name="Patent Discovery Licensing",
        sector=10,
        revenue_models=[
            RevenueModel.LICENSING,
            RevenueModel.IP_ROYALTIES,
        ],
        description="Platform-mediated licensing of AI-identified patentable discoveries.",
    ),
    RevenueEngine(
        engine_id=92,
        name="Invention Marketplace",
        sector=10,
        revenue_models=[
            RevenueModel.MARKETPLACE_FEES,
            RevenueModel.IP_ROYALTIES,
        ],
        description="Marketplace where AI-generated invention concepts are bought and licensed.",
    ),
    RevenueEngine(
        engine_id=93,
        name="Technology Transfer Platform",
        sector=10,
        revenue_models=[
            RevenueModel.LICENSING,
            RevenueModel.VENTURE_PARTNERSHIPS,
        ],
        description="Structured platform for transferring platform-discovered technologies to industry.",
    ),
    RevenueEngine(
        engine_id=94,
        name="Startup Incubation Worlds",
        sector=10,
        revenue_models=[
            RevenueModel.VENTURE_PARTNERSHIPS,
            RevenueModel.PLATFORM_TRANSACTION_CUT,
        ],
        description="Simulated incubation environments where new ventures are modelled and validated.",
    ),
    RevenueEngine(
        engine_id=95,
        name="AI-Generated Product Concepts",
        sector=10,
        revenue_models=[
            RevenueModel.LICENSING,
            RevenueModel.MARKETPLACE_FEES,
        ],
        description="Commercially viable product concepts autonomously generated by platform AI.",
    ),
    RevenueEngine(
        engine_id=96,
        name="Venture Discovery Marketplace",
        sector=10,
        revenue_models=[
            RevenueModel.MARKETPLACE_FEES,
            RevenueModel.VENTURE_PARTNERSHIPS,
        ],
        description="Marketplace connecting AI-discovered opportunities with venture capital.",
    ),
    RevenueEngine(
        engine_id=97,
        name="Innovation Challenge Competitions",
        sector=10,
        revenue_models=[
            RevenueModel.PLATFORM_TRANSACTION_CUT,
            RevenueModel.ENTERPRISE_SAAS,
        ],
        description="Corporate-sponsored innovation challenges run within the platform ecosystem.",
    ),
    RevenueEngine(
        engine_id=98,
        name="Corporate R&D Pipelines",
        sector=10,
        revenue_models=[
            RevenueModel.ENTERPRISE_SAAS,
            RevenueModel.LICENSING,
        ],
        description="Managed R&D simulation pipelines customised for corporate innovation teams.",
    ),
    RevenueEngine(
        engine_id=99,
        name="Breakthrough Discovery Auctions",
        sector=10,
        revenue_models=[
            RevenueModel.MARKETPLACE_FEES,
            RevenueModel.IP_ROYALTIES,
        ],
        description="Time-limited auctions for exclusive rights to high-value AI-generated discoveries.",
    ),
    RevenueEngine(
        engine_id=100,
        name="Global Innovation Exchange",
        sector=10,
        revenue_models=[
            RevenueModel.MARKETPLACE_FEES,
            RevenueModel.VENTURE_PARTNERSHIPS,
            RevenueModel.IP_ROYALTIES,
        ],
        description="Global exchange where discoveries, IP, and innovations are continuously traded.",
    ),
]
